### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by CitizenDev** [CoolRunner-dk/business-central-php#2]
Hey, first of all thanks for the great work done here!

I have a quick question, does it also work with On-premise deployments?

**Comment by ExeQue** [comment]
I haven't been able to test this using the on-premise solution, but if the on-premise solution runs with the same OData V4 implementation as the cloud solution does, then I don't see why it wouldn't.

If you're going to try using this on an on-premise solution then please keep me posted if it works or not.

**Comment by CitizenDev** [comment]
Thanks for the reply, I will definitely test it out soon and let you know.
