### ISSUE TITLE
Guzzle ^7 support

### ISSUE THREAD

**Issue by thomaskenne** [CoolRunner-dk/business-central-php#4]
Hi Morten. 

Thanks for your work!! 

Is it possible to update the guzzle requirements, so it is possible to require it with Laravel 8?

Thanks!

**Comment by thomaskenne** [comment]
illuminate/support should of course also be extended to ^8.0

**Comment by ExeQue** [comment]
The Guzzle requirements has been bumped to 7+ along with Illuminate/Support to 8+
